const express = require("express");
const { registerHotel, updateHotel, getAllHotels, getHotel } = require("../controllers/hotelController");
const authMiddleware = require("../middlewares/authMiddleware");
const checkOwnerMiddleware = require("../middlewares/checkOwnerMiddleware");
const upload = require("../config/upload");
const router = express.Router();
router.post("/hotel", authMiddleware, upload.array("images"), registerHotel);
router.put("/hotel/:id", authMiddleware, checkOwnerMiddleware, upload.array("images"), updateHotel);
router.get("/all", getAllHotels);
router.get("/hotel/:id", getHotel);
module.exports = router;